### ISSUE TITLE
Marker Image

### ISSUE THREAD

**Issue by yasaricli** [Weopt/react-native-here-maps#4]
Can marker images be in the **markerList** ?

that is, if there is a marker image, a default image is used.

for example:

``` JS
const markerList = [
  {
    latitude: location.lat,
    longitude: location.lon,
    title: location.title,
    description: location.description,
    image: require('image_url.png')
  }
]
```

Thanks.

**Comment by Nahani** [comment]
No this parameter is not implemented, you can manually override the marker image present in android/app/src/main/res/drawable
